name: "upload coverage report to codecov"

on:
  push:
    branches:
      - "master"

jobs:
  run:
    name: processing upload coverage (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PHP: '7.4'
    steps:
      - uses: actions/checkout@master
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
